version: '2' 
services:
  nexus:  
    container_name: nexus
    image: sonatype/nexus3
    volumes: 
      - /Users/xuhj/Documents/Docker/data/nexus/data:/nexus-data
    ports: 
      - "8081:8081"

