version: '3'

services:
  postgis: 
    image: jira:latest
    container_name: jira
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /Users/xuhj/Documents/Docker/data/jira:/var/atlassian/jira
    ports:
      - "18009:8080"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4096M
        reservations:
          cpus: 1
          memory: 2048M