version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.100:8929' #若有域名可以写域名
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/Users/xuhj/Documents/Docker/setup/gitlab/config:/etc/gitlab'
      - '/Users/xuhj/Documents/Docker/data/gitlab/logs:/var/log/gitlab'
      - '/Users/xuhj/Documents/Docker/data/gitlab/data:/var/opt/gitlab'