version: '3'
services:
  skywalking:
    image: apache/skywalking-oap-server:8.9.0
    container_name: skywalking
    restart: always
    ports:
      - 1234:1234
      - 11800:11800
      - 12800:12800

  skywalking-ui:
    image: apache/skywalking-ui:8.9.0
    container_name: skywalking-ui
    restart: always
    depends_on:
      - skywalking
    ports:
      - 8080:8080
    environment:
      - SW_OAP_ADDRESS=localhost:12800

