version: '3'

services:
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /Users/xuhj/Documents/Docker/setup/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /Users/xuhj/Documents/Docker/data/redis/data:/data
    command: /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf